<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <ProjectReference Include="../SeWZC.WorldBox.UI/SeWZC.WorldBox.UI.csproj" />
  </ItemGroup>
</Project>
