<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SeWZC.WorldBox.Core/SeWZC.WorldBox.Core.csproj" />
  </ItemGroup>
</Project>
